ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
	config.vm.define "debian-01" do |a|
		a.vm.provider "docker" do |d|
			d.build_dir = "."
			d.build_args = ["-t=debian-01"]
			d.ports = ["8080:8080"]
			d.name = "debian-01"
			d.remains_running = true
			d.cmd = ["/code/main"]
		end
	end
end
